cfengine-acf11:  
  # The location of our core docker directory
  build: ./docker
  # DC build file for this server
  dockerfile: Dockerfile_Tomcat8
  # bind public port to 8081
  ports:
    - "8011:8080"
  volumes:
    - ./docker/ACF11:/usr/local/tomcat/webapps

cfengine-acf10:  
  # The location of our core docker directory
  build: ./docker
  # DC build file for this server
  dockerfile: Dockerfile_Tomcat8
  # bind public port to 8081
  ports:
    - "8010:8080"
  volumes:
    - ./docker/ACF10:/usr/local/tomcat/webapps


cfengine-acf2016:  
  # The location of our core docker directory
  build: ./docker
  # DC build file for this server
  dockerfile: Dockerfile_Tomcat8
  # bind public port to 8081
  ports:
    - "8016:8080"
  volumes:
    - ./docker/ACF2016:/usr/local/tomcat/webapps